micronaut:
  application:
    name: bookMyTickets
  server:
    port: ${PORT:9000}
    context-path: /api
  http:
    client:
      read-timeout: 60
  security:
    enabled: false

datasources:
  default:
    url: ${JDBC_DATABASE_URL:`jdbc:postgresql://localhost:5432/bmt_db`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME:`postgres`}
    password: ${JDBC_DATABASE_PASSWORD:``}

liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase-changelog.xml'
